# frozen_string_literal: true

source 'https://rubygems.org'

gem 'opentelemetry-instrumentation-rails', '~> 0.20.0'
gem 'rack', '~> 2.2.3'
gem 'rails', '~> 6.1.3'
gem 'sqlite3', '~> 1.4'
gem 'uptrace', '~> 1.0.2'

gem "opentelemetry-instrumentation-active_record", "~> 0.2.2"
