apiVersion: 1

datasources:
  - name: Uptrace Tempo Project 1
    type: tempo
    access: proxy
    url: http://uptrace:80/api/tempo/1
    editable: true
    jsonData:
      tlsSkipVerify: true
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Bearer user1_secret'

  - name: Uptrace Prometheus Project 1
    type: prometheus
    access: proxy
    url: http://uptrace:80/api/prometheus/1
    editable: true
    jsonData:
      tlsSkipVerify: true
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Bearer user1_secret'

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
