# Secret key that is used to sign JWT tokens.
secret_key: changeme

# Public URL for Vue-powered UI.
site:
  scheme: 'http'
  host: 'localhost'

listen:
  # OTLP/gRPC API
  grpc: ':14317'
  # OTLP/HTTP API and Uptrace API
  http: ':14318'

ch:
  # Connection string for ClickHouse database.
  # clickhouse://<user>:<password>@<host>:<port>/<database>?sslmode=disable
  dsn: 'clickhouse://default:@clickhouse:9000/uptrace?sslmode=disable'

retention:
  # Tell ClickHouse to delete data after 30 days.
  # Supports SQL interval syntax, for example, INTERVAL 30 DAY.
  ttl: 30 DAY

users:
  - id: 1
    username: uptrace
    password: uptrace

projects:
  # First project is used for self-monitoring.
  - id: 1
    name: Uptrace
    token: secret_token

  - id: 2
    name: My project
    token: secret_token

# Various limits we apply to queries on spans_index table.
#
# - https://clickhouse.com/docs/en/operations/settings/query-complexity/
# - https://clickhouse.com/docs/en/sql-reference/statements/select/sample/
ch_select_limits:
  sample_rows: 10e6 # sample 10 million rows
  max_rows_to_read: 12e6 # read at most 12 million rows
  max_bytes_to_read: 4e9 # read at most 4 gigabytes of data
