CREATE TABLE users (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username varchar(500),
  email varchar(500) NOT NULL,
  password varchar(500),
  avatar varchar(2000) NOT NULL,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

--==============================================================================

CREATE TABLE pinned_facets (
  user_id int8 NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  attr varchar(500),
  unpinned boolean NOT NULL DEFAULT FALSE,

  PRIMARY KEY (user_id, attr)
);
