services:
  clickhouse:
    image: clickhouse/clickhouse-server:26.3
    restart: on-failure
    environment:
      CLICKHOUSE_USER: uptrace
      CLICKHOUSE_PASSWORD: uptrace
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
      start_period: 120s
    volumes:
      - ch_data:/var/lib/clickhouse

  postgres:
    image: postgres:17-alpine
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: uptrace
      POSTGRES_PASSWORD: uptrace
      POSTGRES_DB: uptrace
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U uptrace -d uptrace']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - 'pg_data:/var/lib/postgresql/data/pgdata'

  redis:
    image: redis:6.2.2-alpine
    restart: on-failure
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 1s
      retries: 30

  uptrace:
    image: 'uptrace/uptrace:2.1.0-rc.1'
    restart: on-failure
    volumes:
      - ./uptrace.yml:/etc/uptrace/config.yml
    ports:
      - '14317:4317'
      - '14318:80'
    depends_on:
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.123.0
    restart: on-failure
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - '4317:4317'
      - '4318:4318'
    depends_on:
      - uptrace

  mailpit:
    image: axllent/mailpit
    restart: on-failure
    ports:
      - '8025:8025'
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  redis1:
    image: redislabs/redis:6.2.18-42
    restart: on-failure
    volumes:
      - redislabs_data_1:/opt/redislabs
    ports:
      - '8443:8443'
      - '9443:9443'
      - '12000:12000'
      - '8070:8070'
    privileged: true

  redis2:
    image: redislabs/redis:6.2.18-42
    restart: on-failure
    volumes:
      - redislabs_data_2:/opt/redislabs
    ports:
      - '8444:8443'
      - '9444:9443'
      - '12001:12000'
      - '8071:8070'
    privileged: true

  redis-client:
    build:
      dockerfile: ./redis-client/Dockerfile
      context: .

volumes:
  ch_data:
  pg_data:
  redislabs_data_1:
  redislabs_data_2:
