CREATE TABLE dashboards (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  project_id int4 NOT NULL,
  template_id varchar(500),

  name varchar(1000) NOT NULL,
  pinned boolean NOT NULL,

  grid_query varchar(1000),

  table_metrics jsonb,
  table_query varchar(1000),
  table_grouping jsonb,
  table_column_map jsonb,

  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

--bun:split

CREATE UNIQUE INDEX dashboards_project_id_template_id
ON dashboards (project_id, template_id);

--==============================================================================
--bun:split

DO $$ BEGIN
  CREATE TYPE public.grid_column_type_enum AS ENUM (
    'chart',
    'table',
    'heatmap'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

--bun:split

CREATE TABLE dash_grid_columns (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  project_id int4 NOT NULL,
  dash_id int8 NOT NULL REFERENCES dashboards (id) ON DELETE CASCADE,

  name varchar(1000) NOT NULL,
  description varchar(1000),

  width int4,
  height int4,
  x_axis int4,
  y_axis int4,

  grid_query_template varchar(1000),

  type grid_column_type_enum NOT NULL,
  params jsonb NOT NULL,

  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

--bun:split

CREATE INDEX dash_grid_columns_dash_id_idx
ON dash_grid_columns (dash_id);

--bun:split

CREATE INDEX dash_grid_columns_project_id_idx
ON dash_grid_columns (project_id);

--==============================================================================
--bun:split

DO $$ BEGIN
  CREATE TYPE public.dash_kind_enum AS ENUM (
    'grid',
    'table'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

--bun:split

CREATE TABLE dash_gauges (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  project_id int4 NOT NULL,
  dash_id int8 NOT NULL REFERENCES dashboards (id) ON DELETE CASCADE,
  dash_kind dash_kind_enum NOT NULL,

  name varchar(1000) NOT NULL,
  description varchar(1000),
  index int4,
  template varchar(1000),

  metrics jsonb NOT NULL,
  query varchar(1000) NOT NULL,
  column_map jsonb,

  grid_query_template varchar(1000),

  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

--bun:split

CREATE INDEX dash_gauges_dash_id_idx
ON dash_gauges (dash_id);

--==============================================================================
--bun:split

DO $$ BEGIN
  CREATE TYPE public.metric_instrument_enum AS ENUM (
    'gauge',
    'additive',
    'counter',
    'histogram'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

--bun:split

CREATE TABLE metrics (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  project_id int4 NOT NULL,

  name varchar(1000) NOT NULL,
  description varchar(1000),
  unit varchar(100),
  instrument metric_instrument_enum NOT NULL,
  attr_keys text[],

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

--bun:split

CREATE UNIQUE INDEX metrics_project_id_name_unq
ON metrics (project_id, name);
