  CREATE TYPE public.achiev_name_enum AS ENUM (
    'configure-tracing',
    'configure-metrics',
    'install-collector',
    'create-metric-monitor'
  );

--bun:split

CREATE TABLE achievements (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id int8 REFERENCES users (id) ON DELETE CASCADE,
  project_id int4 REFERENCES projects (id) ON DELETE CASCADE,
  name achiev_name_enum NOT NULL
);

--bun:split

CREATE UNIQUE INDEX achievements_user_id_project_id_name_unq
ON achievements (coalesce(user_id, 0), coalesce(project_id, 0), name);
