CREATE TABLE annotations (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  project_id int4 NOT NULL,
  hash int8,
  name varchar(500) NOT NULL,
  description varchar(5000) NOT NULL,
  color varchar(100) NOT NULL,
  attrs jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

--bun:split

CREATE UNIQUE INDEX annotations_project_id_hash_idx
ON annotations (project_id, hash);
