// Code generated by "stringer -type=TokenID"; DO NOT EDIT.

package chquery

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF_TOKEN-0]
	_ = x[INCLUDE_TOKEN-1]
	_ = x[EXCLUDE_TOKEN-2]
	_ = x[REGEXP_TOKEN-3]
}

const _TokenID_name = "EOF_TOKENINCLUDE_TOKENEXCLUDE_TOKENREGEXP_TOKEN"

var _TokenID_index = [...]uint8{0, 9, 22, 35, 47}

func (i TokenID) String() string {
	if i < 0 || i >= TokenID(len(_TokenID_index)-1) {
		return "TokenID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenID_name[_TokenID_index[i]:_TokenID_index[i+1]]
}
