name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - v1.4.0.alpha
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
